### ISSUE TITLE
Allow to define ClassLoader used to load migration file

### ISSUE THREAD

**Issue by velias** [ozwolf-software/mongo-trek#12]
Trying to use MongoTrek in In Quarkus I hit problem with migration file loading, which looks to be related to classloading (so may maybe occur even in other environments with more complicated classloading).

Simply migration file loaded over `MigrationCommandsFactory.class.getClassLoader().getResource(migrationsFile)` is not found (null is returned), while it is found when I try to load it over classloader of my class.

Simplest solution might be to allow to define which classloader will be used for loading (I saw this in other libraries also) using some setter on `MongoTrek` instance. If not defined then current one will be used.

More complete solution should be to allow to provide migration file as an InputStream, or even String, but they require bigger change.

I can provide PR for this basic change, any chance it will be merged and new version released in some reasonable time frame (I do not want to maintain my clone of this great library).

Thanks in advance.

**Comment by OzWolf** [comment]
Hey...happy to do the change myself.  Was on my radar to do a dependency bump and migrate it onto JUnit5 anyway so I'll add the class loader option while I'm at it.

What I will do is make a static method available on the `MongoTrek` class:

```java
MongoTrek.setClassLoader(ClassLoader classLoader)
```

Define this before doing anything with mongoTrek and this will then become the class loader that is used underneath the hood when loading resources.

Sounds suitable for your needs?

**Comment by velias** [comment]
Works for me, thanks a lot in advance.

**Comment by OzWolf** [comment]
Just a courtesy ping that version `4.1.0` is now in Maven Central with these changes.

**Comment by velias** [comment]
Thanks a lot, really appreciated, works like a charm. BTW any place where we can discuss how migrations concurrency works if multiple instances of the migration process are run at nearly same time (starting multiple microservice nodes in OpenShift platform)? Maybe worth to mention this in the doc.
