### ISSUE TITLE
Aggregation example

### ISSUE THREAD

**Issue by Piotr-Filochowski** [ozwolf-software/mongo-trek#14]
Hi,

i think this project is super cool and would like to use it, but i'm struggling with implementing here more sophisticated migration scripts. Could you provide some examples of for example aggregations implemented with use of your lib?

**Comment by OzWolf** [comment]
Apologies for not getting back on this one...had some issues with GitHub notifications (by issue I mean I accidentally turned off my reminders and notifications to this repo).

Issue #1 provides an example by myself on how to use a mapReduce, aggregation and drop command to change the type of a field in a collection.
